[package]
name = "qbsdiff"
version = "0.1.2"
authors = ["hucsmn <hucsmn@hotmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
keywords = ["bsdiff", "delta"]
homepage = "https://github.com/hucsmn/qbsdiff"
repository = "https://github.com/hucsmn/qbsdiff"
description = "Fast and memory saving bsdiff 4.x compatible delta compressor and patcher."

[dependencies]
bzip2 = "0.3"
byteorder = "1.3"
suffix_array = "0.4"
clap = { optional = true, version = "2.33" }

[dev-dependencies]
globwalk = "0.7"
subprocess = "0.1"
rand = "0.7"
chrono = "0.4"

[features]
default = []
cmd = ["clap"]

[[bin]]
name = "qbsdiff"
path = "cmd/qbsdiff.rs"
required-features = ["cmd"]

[[bin]]
name = "qbspatch"
path = "cmd/qbspatch.rs"
required-features = ["cmd"]

[[test]]
name = "compat"
path = "tests/compat.rs"
